# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
 devices([
    "iPhone 8 Plus",
    "iPhone SE (1st generation)",
    "iPhone 12 Pro Max"

 ])

 languages([
  "en-US",
])

# The name of the scheme which contains the UI Tests
  scheme("TheNewFlickrUITests")

# Where should the resulting screenshots be stored?
  output_directory "./fastlane/screenshots"
 
# remove the '#' to clear all previously generated screenshots before creating new ones
  clear_previous_screenshots(true)

# Remove the '#' to set the status bar to 9:41 AM, and show full battery and reception. See also override_status_bar_arguments for custom options.
#  override_status_bar(true)

